// Compact hand-written Russian → English-term map for icon search (~150 common
// words). NOT a mirror of the catalog: an unknown Russian word simply expands to
// nothing (see `expandRu`). Values are English terms matched against icon
// names, aliases and lucide tags.
//
// Matching is stem-tolerant: a map key applies to a query word when
// `key.startsWith(word) || word.startsWith(key)` (see expandRu), so "дом",
// "дома", "домик" all reach the "дом" entry.
export const RU_ICON_SYNONYMS: Record<string, string[]> = {
  дом: ["house", "home"],
  домой: ["house", "home"],
  здание: ["building"],
  квартира: ["building", "house"],
  огонь: ["flame", "fire"],
  пламя: ["flame", "fire"],
  пожар: ["flame", "fire"],
  папка: ["folder"],
  файл: ["file"],
  документ: ["file-text", "file"],
  замок: ["lock", "castle"],
  ключ: ["key"],
  щит: ["shield"],
  защита: ["shield", "lock"],
  безопасность: ["shield", "lock"],
  пользователь: ["user"],
  человек: ["user", "person"],
  люди: ["users"],
  группа: ["users"],
  сердце: ["heart"],
  любовь: ["heart"],
  звезда: ["star"],
  избранное: ["star", "bookmark"],
  закладка: ["bookmark"],
  флаг: ["flag"],
  метка: ["tag", "pin"],
  тег: ["tag"],
  булавка: ["pin"],
  колокол: ["bell"],
  уведомление: ["bell"],
  почта: ["mail"],
  письмо: ["mail", "send"],
  конверт: ["mail"],
  телефон: ["phone"],
  звонок: ["phone", "bell"],
  сообщение: ["message-circle", "message-square"],
  чат: ["message-circle"],
  комментарий: ["message-square"],
  ссылка: ["link"],
  скрепка: ["paperclip"],
  вложение: ["paperclip"],
  картинка: ["image"],
  изображение: ["image"],
  фото: ["camera", "image"],
  камера: ["camera"],
  видео: ["video", "film"],
  фильм: ["film"],
  музыка: ["music"],
  наушники: ["headphones"],
  микрофон: ["mic"],
  звук: ["volume", "music"],
  громкость: ["volume"],
  код: ["code"],
  терминал: ["terminal"],
  консоль: ["terminal"],
  база: ["database"],
  сервер: ["server"],
  облако: ["cloud"],
  процессор: ["cpu"],
  настройки: ["settings"],
  шестерёнка: ["settings"],
  инструмент: ["wrench", "hammer"],
  гаечный: ["wrench"],
  молоток: ["hammer"],
  молния: ["zap"],
  ракета: ["rocket"],
  лампочка: ["lightbulb"],
  идея: ["lightbulb"],
  мозг: ["brain"],
  искры: ["sparkles"],
  волшебство: ["wand-sparkles", "sparkles"],
  магия: ["wand-sparkles"],
  цель: ["target"],
  мишень: ["target"],
  трофей: ["trophy"],
  награда: ["award", "trophy"],
  подарок: ["gift"],
  корзина: ["shopping-cart", "trash"],
  тележка: ["shopping-cart"],
  покупки: ["shopping-cart", "shopping-bag"],
  карта: ["credit-card", "map"],
  деньги: ["dollar-sign", "wallet", "banknote"],
  доллар: ["dollar-sign"],
  кошелёк: ["wallet"],
  оплата: ["credit-card"],
  график: ["chart-bar", "chart-line", "trending-up"],
  диаграмма: ["chart-pie", "chart-bar"],
  статистика: ["chart-bar", "activity"],
  активность: ["activity"],
  глобус: ["globe"],
  мир: ["globe"],
  земля: ["globe"],
  компас: ["compass"],
  самолёт: ["plane"],
  машина: ["car"],
  автомобиль: ["car"],
  грузовик: ["truck"],
  поезд: ["train"],
  велосипед: ["bike"],
  кофе: ["coffee"],
  еда: ["utensils", "coffee"],
  лист: ["leaf"],
  дерево: ["tree", "tree-deciduous"],
  цветок: ["flower"],
  солнце: ["sun"],
  луна: ["moon"],
  погода: ["cloud", "sun"],
  дождь: ["cloud-rain"],
  снег: ["snowflake", "cloud-snow"],
  ветер: ["wind"],
  глаз: ["eye"],
  просмотр: ["eye"],
  поиск: ["search"],
  лупа: ["search"],
  фильтр: ["funnel"],
  карандаш: ["pencil"],
  редактировать: ["pencil", "pen"],
  ручка: ["pen"],
  удалить: ["trash-2", "x"],
  мусор: ["trash-2"],
  архив: ["archive"],
  скачать: ["download"],
  загрузить: ["upload", "download"],
  выгрузить: ["upload"],
  поделиться: ["share-2"],
  копировать: ["copy"],
  принтер: ["printer"],
  печать: ["printer"],
  сохранить: ["save"],
  дискета: ["save"],
  предупреждение: ["triangle-alert"],
  ошибка: ["circle-alert", "triangle-alert"],
  информация: ["info"],
  вопрос: ["circle-question-mark"],
  помощь: ["circle-question-mark"],
  цитата: ["quote"],
  решётка: ["hash"],
  процент: ["percent"],
  палитра: ["palette"],
  цвет: ["palette"],
  слои: ["layers"],
  сетка: ["layout-grid", "grid"],
  таблица: ["table"],
  коробка: ["box", "package"],
  посылка: ["package"],
  монитор: ["monitor"],
  экран: ["monitor"],
  жук: ["bug"],
  баг: ["bug"],
  ошибкапрограммы: ["bug"],
  плюс: ["plus"],
  минус: ["minus"],
  крест: ["x"],
  галочка: ["check"],
  стрелка: ["arrow-right", "arrow-up", "arrow-down", "arrow-left"],
  вверх: ["arrow-up", "chevron-up"],
  вниз: ["arrow-down", "chevron-down"],
  влево: ["arrow-left", "chevron-left"],
  вправо: ["arrow-right", "chevron-right"],
  назад: ["arrow-left", "undo"],
  вперёд: ["arrow-right", "redo"],
  обновить: ["refresh-cw", "rotate-cw"],
  часы: ["clock"],
  время: ["clock", "timer"],
  таймер: ["timer"],
  календарь: ["calendar"],
  дата: ["calendar"],
  список: ["list"],
  меню: ["menu"],
  плей: ["play"],
  пауза: ["pause"],
  стоп: ["square"],
  замочек: ["lock"],
  разблокировать: ["lock-open", "unlock"],
  корона: ["crown"],
  флажок: ["flag"],
  бомба: ["bomb"],
  щитпроверка: ["shield-check"],
  wifi: ["wifi"],
  вайфай: ["wifi"],
  батарея: ["battery"],
  зарядка: ["battery-charging", "plug"],
  розетка: ["plug"],
  принтерсеть: ["printer"],
};
